### ISSUE TITLE
Czcionki i kolory

### ISSUE THREAD

**Issue by strzempo** [konserw/pyOffer#3]
Preferowane czcionki: Century Gothic. Jeśli problem, to ewent. Arial.
Tabelka lepiej wyglądała w odcieniach szarości zamiast błękitów.

**Comment by konserw** [comment]
Century Gothic nie jest darmowa do komercyjnego stosowania, (Arial chyba też), wybrałem [Montserrat](https://fonts.google.com/specimen/Montserrat?query=Montserrat&preview.text=za%C5%BC%C3%B3%C5%82%C4%87&preview.text_type=custom&sidebar.open&selection.family=Montserrat) Powinna być w miarę podobna do century gothic

**Comment by konserw** [comment]
zrobione w 0.5

**Comment by strzempo** [comment]
Przecież Arial to systemowa czcionka.Wysłane z tabletu Samsung.
-------- Oryginalna wiadomość --------Od: Kamil Strzempowicz <notifications@github.com> Data: 27.04.2020  17:59  (GMT+01:00) Do: konserw/pyOffer <pyOffer@noreply.github.com> DW: strzempo <strzempo@tlen.pl>, Author <author@noreply.github.com> Temat: Re: [konserw/pyOffer] Czcionki i kolory (#3) 

Century Gothic nie jest darmowa do komercyjnego stosowania, (Arial chyba też), wybrałem Montserrat Powinna być w miarę podobna do century gothic



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/konserw/pyOffer/issues/3#issuecomment-620076729",

"url": "https://github.com/konserw/pyOffer/issues/3#issuecomment-620076729",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
