### ISSUE TITLE
Dodawanie klientów

### ISSUE THREAD

**Issue by strzempo** [konserw/pyOffer#5]
Dodawanie klientów nie działa? Jak mam dodać?

**Comment by konserw** [comment]
No jeszcze nie ma. Mozesz mi wyslac a ja dodam w bazie

czw., 7 maj 2020, 08:41 użytkownik strzempo <notifications@github.com>
napisał:

**Comment by konserw** [comment]
będzie w 0.8

**Comment by konserw** [comment]
ok ?
