### ISSUE TITLE
Tabela oferty

### ISSUE THREAD

**Issue by strzempo** [konserw/pyOffer#6]
Nie można przesuwać wierszy.

**Comment by konserw** [comment]
działa już?

**Comment by strzempo** [comment]
YesWysłane z tabletu Samsung.
-------- Oryginalna wiadomość --------Od: Kamil Strzempowicz <notifications@github.com> Data: 01.06.2020  12:47  (GMT+01:00) Do: konserw/pyOffer <pyOffer@noreply.github.com> DW: strzempo <strzempo@tlen.pl>, Author <author@noreply.github.com> Temat: Re: [konserw/pyOffer] Tabela oferty (#6) 

działa już?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/konserw/pyOffer/issues/6#issuecomment-636779157",

"url": "https://github.com/konserw/pyOffer/issues/6#issuecomment-636779157",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
