### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by strzempo** [konserw/pyOffer#7]
Logo trochę za duże - powinno mieć szerokość 30 mm.

**Comment by konserw** [comment]
już jest ok?

**Comment by strzempo** [comment]
TakWysłane z tabletu Samsung.
-------- Oryginalna wiadomość --------Od: Kamil Strzempowicz <notifications@github.com> Data: 01.06.2020  12:46  (GMT+01:00) Do: konserw/pyOffer <pyOffer@noreply.github.com> DW: strzempo <strzempo@tlen.pl>, Author <author@noreply.github.com> Temat: Re: [konserw/pyOffer] Logo (#7) 

już jest ok?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/konserw/pyOffer/issues/7#issuecomment-636778985",

"url": "https://github.com/konserw/pyOffer/issues/7#issuecomment-636778985",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
